name: Node.js CI

on:
  pull_request:
    branches: ["main", "dev"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    defaults:
      run:
        working-directory: ./app

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "npm"
          cache-dependency-path: app/package-lock.json
      
      - name: Install dependencies
        run: npm ci

      - name: Create .env file
        run: echo ${{secrets.ENV_VARS}} > .env
        
      - name: Set env vars
        run: export $(cat .env | xargs)
        
      - name: Build files (if applicable)
        run: npm run build --if-present
        
      - name: Run tests
        run: npm test
